// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFirst.Data;

#nullable disable

namespace WebApiFirst.Migrations
{
    [DbContext(typeof(AnimalesContext))]
    [Migration("20240713202618_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiFirst.Models.Animal", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalID"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("EspecieID")
                        .HasColumnType("int");

                    b.Property<int>("HabitatID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalID");

                    b.HasIndex("EspecieID");

                    b.HasIndex("HabitatID");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("WebApiFirst.Models.Especie", b =>
                {
                    b.Property<int>("EspecieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecieID"));

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecieID");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("WebApiFirst.Models.Habitat", b =>
                {
                    b.Property<int>("HabitatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitatID"));

                    b.Property<string>("Clima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HabitatID");

                    b.ToTable("Habitats");
                });

            modelBuilder.Entity("WebApiFirst.Models.Animal", b =>
                {
                    b.HasOne("WebApiFirst.Models.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiFirst.Models.Habitat", "Habitat")
                        .WithMany()
                        .HasForeignKey("HabitatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Habitat");
                });
#pragma warning restore 612, 618
        }
    }
}
